site_name: BNAP - Bitcoin Native Asset Protocol
site_description: Comprehensive documentation for the Bitcoin Native Asset Protocol system
site_author: BNAP Development Team
site_url: https://bnap-docs.github.io

repo_name: bnap/bnap
repo_url: https://github.com/bnap/bnap
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: guides/getting-started.md
    - Installation: deployment/installation.md
    - First Steps: guides/first-steps.md
  - Technical Documentation:
    - Architecture Overview: technical/architecture.md
    - Protocol Specification: technical/protocol.md
    - Cryptographic Primitives: technical/cryptography.md
    - Asset Commitments: technical/commitments.md
    - Network Protocol: technical/network.md
    - Transaction Formats: technical/transactions.md
  - API Documentation:
    - Overview: api/overview.md
    - REST API: api/rest.md
    - Python API: api/python.md
    - JavaScript SDK: api/javascript.md
    - Error Codes: api/errors.md
    - Examples: api/examples.md
  - User Guides:
    - Fungible Tokens: guides/fungible-tokens.md
    - NFT Collections: guides/nft-collections.md
    - Allowlists & Merkle Proofs: guides/allowlists.md
    - CLI Commands: guides/cli-reference.md
    - Integration Guide: guides/integration.md
  - Deployment:
    - System Requirements: deployment/requirements.md
    - Installation Guide: deployment/installation.md
    - Configuration: deployment/configuration.md
    - Bitcoin Node Setup: deployment/bitcoin-node.md
    - Docker Deployment: deployment/docker.md
    - Production Checklist: deployment/production.md
  - Operations:
    - Monitoring: operations/monitoring.md
    - Backup & Recovery: operations/backup.md
    - Performance Tuning: operations/performance.md
    - Troubleshooting: operations/troubleshooting.md
    - Security Hardening: operations/security.md
    - Upgrades: operations/upgrades.md
  - Reference:
    - Glossary: reference/glossary.md
    - Data Structures: reference/data-structures.md
    - Transaction Examples: reference/transactions.md
    - Test Vectors: reference/test-vectors.md
    - FAQ: reference/faq.md
    - External Resources: reference/external.md

theme:
  name: material
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
    logo: material/bitcoin

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ?
          'dark' : 'light'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: bnap
      repo: bnap
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bnap/bnap
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bnap_protocol
  generator: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: >
  Copyright &copy; 2024 BNAP Development Team –
  <a href="#__consent">Change cookie settings</a>